version: '3.3'

volumes:
  lifemanager_postgres_volume:

services:
  back:
    build: .
    container_name: back

  front:
    build: front/
    container_name: front
    ports:
      - 80:3000

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: lifemanager
      POSTGRES_PASSWORD: postgres
    volumes:
      - lifemanager_postgres_volume:/var/lib/postgresql/data
