version: '3.3'

volumes:
  lifemanager_postgres_volume:

secrets:
  jwt_master_password:
    file: ./jwt-master-password.txt

services:
  back:
    build: .
    container_name: back
    ports:
      - 7000:7000
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      FRONT_URL: front
      JWT_SECRET: jwt_master_password
    secrets:
      - jwt_master_password
    networks:
      - life-manager

  front:
    build:
      context: front/.
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 80:80
    networks:
      - life-manager

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - lifemanager_postgres_volume:/var/lib/postgresql/data
    networks:
      - life-manager

networks:
  life-manager:
