server:
  port: 80
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATA_POSTGRES_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

logging:
  level:
    root: INFO

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

jwt:
  secret: ENC(ho3x09YFe9sLlcHEaZb86nYoj/XB+o+GOsN5mxjIVUM=)

life-manager:
  front-url: http://localhost:3000
  keepRecentlyDeletedCategoriesDays: 30

